# Name of website
title: Joshua Hanna

# Short description of website
description:

# Your name
author: Joshua Hanna

# Your profile image (like Facebook)
selfie: /assets/img/profile.jpg

# Your email address
email: jmarkh10@gmail.com

baseurl: https://joshuahanna.com

permalink: /:categories/:title/

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

theme: jekyll-theme-minimal