permalink:           pretty

# Setup
title:               A Fool and his Money
tagline:             'Parting ways with cents'
description:         'Keeping myself financially accountable and learning a lot along the way.'
url:                 http://jmarksh.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joshua Hanna
  url:               https://jmarksh.github.io/
  email:             contact@joshuahanna.com

# Custom vars
version:             1.0.0
