# Basics
title: Joshua Hanna
description:
author: Joshua Hanna
selfie: /assets/img/profile.jpg
email: jmarkh10@gmail.com

baseurl: https://joshuahanna.com

permalink: /:categories/:title/

collections:
  category:
    output: true
    permalink: /blog/categories/:name
  tag:
    output: true
    permalink: /blog/tags/:name

defaults:
  - scope:
      path: ""
      type: post
    values:
      layout: "post"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: category
    values:
      layout: "category"
  - scope:
      path: ""
      type: tag
    values:
      layout: "tag"
