url: http://jmarksh.github.io/
collections:
  programs:
    output: true
	permalink: /programs/:path/
  personnel:

defaults:
  - scope:
      path: ""
      type: "programs"
    values:
      layout: "program"
  - scope:
      path: ""
    values:
      layout: "default"